# Generated by Django 6.0.4 on 2026-04-17 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '社团成员',
                'verbose_name_plural': '社团成员',
                'unique_together': {('club', 'user')},
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='club',
                    name='members',
                    field=models.ManyToManyField(blank=True, related_name='joined_clubs', through='clubs.Membership', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="INSERT INTO clubs_membership(club_id, user_id, is_admin, joined_at) SELECT club_id, user_id, 0, CURRENT_TIMESTAMP FROM clubs_club_members;",
            reverse_sql="DELETE FROM clubs_membership WHERE is_admin = 0;",
        ),
    ]
