# Generated by Django 6.0.4 on 2026-04-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_crossschoolevent_knowledgecategory_knowledgeitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossschoolevent',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
    ]
