# Generated by Django 6.0.4 on 2026-04-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_crossschoolevent_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('sports', '体育竞技类'), ('arts', '文艺表演类'), ('culture', '传统文化类'), ('academic', '学术科创类'), ('public_welfare', '公益实践类'), ('interest', '兴趣生活类'), ('other', '其他类')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='club_posters/'),
        ),
    ]
