# Generated by Django 6.0.4 on 2026-04-19 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_category_club_poster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti', models.CharField(blank=True, help_text='如：INTJ, ENFP等', max_length=4, null=True, verbose_name='MBTI性格类型')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('interests', models.TextField(blank=True, help_text='用逗号分隔，如：篮球,音乐,编程', verbose_name='兴趣标签')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='启用通知')),
                ('email_notification', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
