# Generated by Django 6.0.4 on 2026-04-20 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_profile_options_remove_profile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户资料', 'verbose_name_plural': '用户资料'},
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='建议尺寸 400x400，系统会自动居中裁剪', null=True, upload_to='profile_images/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti_type',
            field=models.CharField(blank=True, help_text='如：INTJ, ENFP等', max_length=4, null=True, verbose_name='MBTI性格类型'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
