# Generated by Django 6.0.4 on 2026-04-20 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_profile_options_profile_profile_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crossschoolevent',
            name='category',
            field=models.CharField(choices=[('sports', '体育竞技类'), ('arts', '文艺表演类'), ('culture', '传统文化类'), ('academic', '学术科创类'), ('public_welfare', '公益实践类'), ('interest', '兴趣生活类'), ('other', '其他类')], default='other', max_length=20, verbose_name='活动标签'),
        ),
        migrations.AddField(
            model_name='crossschoolevent',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='报名上限'),
        ),
        migrations.AddField(
            model_name='crossschoolevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_events', to=settings.AUTH_USER_MODEL, verbose_name='报名成员'),
        ),
        migrations.AddField(
            model_name='crossschoolevent',
            name='scope',
            field=models.CharField(choices=[('club_activity', '社团活动'), ('faculty_activity', '院级活动'), ('school_activity', '校级活动')], default='club_activity', max_length=20, verbose_name='活动级别'),
        ),
    ]
