# Generated by Django 6.0.4 on 2026-04-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_crossschoolevent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossschoolevent',
            name='partner_school',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
