# Generated by Django 6.0.4 on 2026-04-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_crossschoolevent_partner_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossschoolevent',
            name='flow',
            field=models.TextField(blank=True, verbose_name='活动流程'),
        ),
        migrations.AddField(
            model_name='crossschoolevent',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='活动地点'),
        ),
        migrations.AddField(
            model_name='crossschoolevent',
            name='precautions',
            field=models.TextField(blank=True, verbose_name='注意事项'),
        ),
        migrations.AddField(
            model_name='crossschoolevent',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='活动目的'),
        ),
        migrations.AlterField(
            model_name='crossschoolevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='活动简介'),
        ),
        migrations.AlterField(
            model_name='crossschoolevent',
            name='end_date',
            field=models.DateField(verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='crossschoolevent',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='公开活动'),
        ),
        migrations.AlterField(
            model_name='crossschoolevent',
            name='start_date',
            field=models.DateField(verbose_name='开始日期'),
        ),
    ]
