# Generated by Django 6.0.4 on 2026-04-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_postcomment_postlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pinned', '-pinned_at', '-created_at'], 'verbose_name': '动态', 'verbose_name_plural': '动态'},
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AddField(
            model_name='post',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='置顶时间'),
        ),
    ]
