# Generated by Django 6.0.4 on 2026-04-21 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_alter_post_options_post_is_pinned_post_pinned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncyclopediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL别名')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('icon', models.CharField(default='bi-book', max_length=50, verbose_name='图标类名')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '百科分类',
                'verbose_name_plural': '百科分类',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EncyclopediaArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL别名')),
                ('summary', models.TextField(blank=True, verbose_name='简介')),
                ('content', models.TextField(verbose_name='正文内容')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='封面图片URL')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='内容来源URL')),
                ('source_name', models.CharField(default='百度百科', max_length=100, verbose_name='来源名称')),
                ('views', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('is_featured', models.BooleanField(default=False, verbose_name='精选')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='clubs.encyclopediacategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '百科文章',
                'verbose_name_plural': '百科文章',
                'ordering': ['-is_featured', '-views', '-created_at'],
                'indexes': [models.Index(fields=['title'], name='clubs_encyc_title_f2848c_idx'), models.Index(fields=['slug'], name='clubs_encyc_slug_79424a_idx')],
            },
        ),
    ]
