# Generated by Django 6.0.4 on 2026-04-21 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_encyclopediacategory_encyclopediaarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossschoolevent',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_events', to='clubs.club'),
        ),
    ]
