# Generated by Django 6.0.4 on 2026-04-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_crossschoolevent_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='一句话介绍自己，展示在个人主页（500字以内）', max_length=500, verbose_name='个人签名'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='profile',
            name='class_name',
            field=models.CharField(blank=True, help_text='如：计算机2024级1班', max_length=50, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('secret', '保密'), ('male', '男'), ('female', '女')], default='secret', max_length=10, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, help_text='所学专业', max_length=100, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_url',
            field=models.URLField(blank=True, help_text='个人博客或社交媒体链接', verbose_name='个人网站'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='用于接收活动通知', max_length=20, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, help_text='你的学号', max_length=20, verbose_name='学号'),
        ),
    ]
