# Generated by Django 6.0.4 on 2026-04-22 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_profile_bio_profile_birthday_profile_class_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRecommendationData',
            fields=[
                ('club_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recommendation_data', serialize=False, to='clubs.club')),
                ('active_time', models.JSONField(blank=True, default=dict, verbose_name='主要活动时间段')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('apply_count', models.IntegerField(default=0, verbose_name='申请次数')),
                ('recommendation_score', models.FloatField(default=0, verbose_name='推荐指数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '社团推荐数据',
                'verbose_name_plural': '社团推荐数据',
                'db_table': 'club_recommendation_data',
            },
        ),
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('category', models.CharField(choices=[('sports', '体育运动'), ('arts', '文艺表演'), ('culture', '传统文化'), ('academic', '学术科创'), ('public_welfare', '公益实践'), ('interest', '兴趣生活')], max_length=20, verbose_name='所属分类')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='标签描述')),
                ('heat', models.IntegerField(default=0, verbose_name='热度')),
            ],
            options={
                'verbose_name': '兴趣标签',
                'verbose_name_plural': '兴趣标签',
                'db_table': 'interest_tag',
                'ordering': ['-heat'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(verbose_name='社团ID')),
                ('feedback_type', models.CharField(choices=[('click', '点击查看'), ('like', '感兴趣'), ('dislike', '不感兴趣'), ('apply', '申请加入'), ('ignore', '忽略')], max_length=20, verbose_name='反馈类型')),
                ('original_score', models.FloatField(default=0, verbose_name='推荐分数')),
                ('reason', models.TextField(blank=True, help_text='用户选择不感兴趣的原因', verbose_name='原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '推荐反馈',
                'verbose_name_plural': '推荐反馈',
                'db_table': 'recommendation_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilarityMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_type', models.CharField(choices=[('user_user', '用户-用户相似度'), ('item_item', '物品-物品相似度'), ('user_club', '用户-社团偏好矩阵')], max_length=20, verbose_name='矩阵类型')),
                ('entity_a', models.IntegerField(verbose_name='实体A ID')),
                ('entity_b', models.IntegerField(verbose_name='实体B ID')),
                ('similarity', models.FloatField(help_text='-1到1或0到1', verbose_name='相似度')),
                ('algorithm', models.CharField(default='cosine', max_length=50, verbose_name='算法')),
                ('sample_size', models.IntegerField(default=0, help_text='计算时使用的样本数量', verbose_name='样本数')),
                ('computed_at', models.DateTimeField(auto_now_add=True, verbose_name='计算时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '相似度矩阵',
                'verbose_name_plural': '相似度矩阵',
                'db_table': 'similarity_matrix',
                'indexes': [models.Index(fields=['matrix_type', 'entity_a', 'entity_b'], name='similarity__matrix__5a5573_idx'), models.Index(fields=['matrix_type', '-similarity'], name='similarity__matrix__ebfde6_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1, null=True, verbose_name='性别')),
                ('grade', models.CharField(blank=True, choices=[('1', '大一'), ('2', '大二'), ('3', '大三'), ('4', '大四'), ('5', '大五'), ('6', '研究生'), ('7', '博士')], max_length=2, null=True, verbose_name='年级')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('academy', models.CharField(blank=True, max_length=100, null=True, verbose_name='学院')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('active_time', models.JSONField(blank=True, default=dict, verbose_name='活跃时间偏好')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='ClubTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, verbose_name='标签权重')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_tags', to='clubs.club')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='clubs.interesttag')),
            ],
            options={
                'verbose_name': '社团标签',
                'verbose_name_plural': '社团标签',
                'db_table': 'club_tag',
                'unique_together': {('club', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(verbose_name='社团ID')),
                ('score', models.FloatField(help_text='0-100', verbose_name='推荐分数')),
                ('grade_score', models.FloatField(default=0, verbose_name='年级匹配度')),
                ('major_score', models.FloatField(default=0, verbose_name='专业匹配度')),
                ('category_score', models.FloatField(default=0, verbose_name='分类匹配度')),
                ('tags_score', models.FloatField(default=0, verbose_name='标签匹配度')),
                ('active_time_score', models.FloatField(default=0, verbose_name='时间匹配度')),
                ('cf_score', models.FloatField(default=0, help_text='协同过滤算法得分', verbose_name='协同过滤分数')),
                ('reasons', models.JSONField(default=list, verbose_name='推荐理由')),
                ('algorithm', models.CharField(choices=[('weighted', '加权匹配'), ('cf_user', '用户协同过滤'), ('cf_item', '物品协同过滤'), ('hybrid', '混合推荐')], max_length=50, verbose_name='算法')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='是否查看')),
                ('is_interested', models.BooleanField(blank=True, null=True, verbose_name='是否感兴趣')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '推荐结果',
                'verbose_name_plural': '推荐结果',
                'db_table': 'recommendation_result',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['user', '-score'], name='recommendat_user_id_0dd32c_idx'), models.Index(fields=['created_at'], name='recommendat_created_d49690_idx')],
                'unique_together': {('user', 'club_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, verbose_name='兴趣权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='选择时间')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='clubs.interesttag')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='clubs.studentprofile')),
            ],
            options={
                'verbose_name': '学生兴趣',
                'verbose_name_plural': '学生兴趣',
                'db_table': 'student_interest',
                'unique_together': {('student', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(blank=True, null=True, verbose_name='社团ID')),
                ('activity_id', models.IntegerField(blank=True, null=True, verbose_name='活动ID')),
                ('behavior_type', models.CharField(choices=[('view', '浏览'), ('like', '收藏'), ('apply', '申请'), ('attend', '参加活动'), ('rate', '评分'), ('share', '分享'), ('comment', '评论')], max_length=20, verbose_name='行为类型')),
                ('weight', models.FloatField(default=1.0, verbose_name='行为权重')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='上下文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='行为时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'db_table': 'user_behavior',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'behavior_type'], name='user_behavi_user_id_f01d25_idx'), models.Index(fields=['club_id', 'behavior_type'], name='user_behavi_club_id_da6a08_idx')],
            },
        ),
    ]
